= J-Voting
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: j-voting
:repository: J-Voting

image:https://github.com/{gitHubUserName}/{repository}/workflows/J-Voting%20CI/badge.svg["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Last release", link="http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22{groupId}%22%20a%3A%22{artifactId}%22"]
image:http://www.javadoc.io/badge/{groupId}/{artifactId}.svg["Javadoc", link="http://www.javadoc.io/doc/{groupId}/{artifactId}"]

A Java project developed with students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises[L3 MIAGE Alternance]).

The code is hereby published under the MIT License, with the permission of the contributors.

The project documentation is link:Doc/README.adoc[here].

== Iteration UML 1

=== Scrum-Master

Maxime

=== Duo 1 and task

Firas ans Chahid => Documentation of bugs

=== Duo 2 and task

Hugo and Nicolas => Export in DOT format

=== Duo 3 and task

Lucas and Sylvain => Set URL preflib

== Iteration UML 2

=== Scrum-Master

Chahid

=== Duo 1 and task

Firas and Hugo  => Implementation of a class and sequence diagram (Decorator)

=== Duo 2 and task

Lucas and Nicolas => Adjustments and export in DOT format 

=== Duo 3 and task

Maxime and Sylvain => Import an external profile via an url (preflib)

== Iteration UML 3

=== Scrum-Master

Firas

=== Duo 1 and task

Maxime and Hugo  => Complete the class diagram and correct the sequence diagram (Decorator)

=== Duo 2 and task

Nicloas and Sylvain => Documentation package management and MutableCompletePreference 

=== Duo 3 and task

Chahid and Lucas => Improvement of the new GUI and modification of the profile doc

== Iteration UML 4

=== Scrum-Master

Lucas

=== Duo 1 and task

Hugo and Sylvain => Ils continuent le travail commencé dans cette PR #9 : https://github.com/oliviercailloux-org/projet-j-voting/pull/9#pullrequestreview-635973419 .Ils souhaitent corriger et compléter les diagrammes de classe et de séquence liés au decorator.

=== Duo 2 and task

Chahid and Firas => Preflib and GUI, leur travail fait suite à cette PR #11 : https://github.com/oliviercailloux-org/projet-j-voting/pull/11#pullrequestreview-635983537

=== Duo 3 and task

Nicolas and Maxime => DOT export,  enfin, Nicolas et Maxime souhaitent continuer le travail entamé dans cette PR #12 : https://github.com/oliviercailloux-org/projet-j-voting/pull/12#pullrequestreview-636054061

== Iteration UML 5

=== Scrum-Master

Sylvain

=== Duo 1 and task

Nicolas and Firas => Modifier la page « Import/Export methods » depuis les éléments proposés dans la PR #26 : https://github.com/oliviercailloux-org/projet-j-voting/pull/26

Pour être plus précis, ils vont effectuer les modifications suivantes :

- Rendre moins « verbeuse » la documentation.
- Rajouter la méthode convertToDot() dans le diagramme d’ExportDOT.
- Retirer la méthode surchargée export() prenant une préférence en argument. 
- Documenter le plug-in d’Eclipse (https://github.com/eclipse/gef/wiki/DOT-User-Guide) et indiquer qu’il fonctionne bien avec les méthodes proposées. 
- Proposer un lien vers les exemples de René Nyffenegger (au bon endroit) que vous nous avez montré en Java. Ses exemples sont très explicites et très variés et pourraient être utiles à la compréhension du format DOT (…) aux groupes futurs. 

=== Duo 2 and task

Hugo et Chahid => Corrections demandées dans la PR #28 : https://github.com/oliviercailloux-org/projet-j-voting/pull/28

=== Duo 3 and task

Lucas and Maxime => Corrections demandées dans la PR #25 : https://github.com/oliviercailloux-org/projet-j-voting/pull/25#pullrequestreview-652408576

Pour être plus précis, ils vont effectuer les modifications suivantes :

- Corriger les erreurs de convention de nommage.
- Ne pas répéter les opérations dans les classes qui implémentent une interface dans le diagramme de classe.
- Corriger le fait que MLID n'est pas détenu par MLPI dans le diagramme de classe.
- Pas de méthode verifyModification sur GraphView dans le diagramme de séquence.

== Iteration 1 JAVA

=== Scrum-Master

Firas

=== Duo 1 and task

Maxime and Hugo  => Implement the classes of the new profile architecture

- Vérifier que toutes les méthodes de l’interface Preference sont correctement implémentées (comme cela est suggéré dans la documentation : https://github.com/oliviercailloux-org/projet-j-voting/blob/main/Doc/chapters/preferenceInterfaces.adoc)
- Modifier les méthodes #addEquivalence et #setAsLeastAsGood de la classe MutablePreference
- Ajouter #asStrictGraph dans Preference
- Ajouter #equals dans ImmutablePreference
- Dans les méthodes #addAlternative, #removeAlternative et #swap de la classe MutableLinearPreference, lever une exception si les alternatives sont déjà où ne sont pas déjà dans le graphe, empêchant la méthode d’effectuer l’action demandée.
- Permettre de récupérer un NavigableSet d’alternatives depuis une ImmutableLinearPreference
Ces dernières propositions proviennent de la section « à envisager » (https://github.com/oliviercailloux/projets/blob/master/J-Voting.adoc) et pourront faire l'objet d'une autre itération.

=== Duo 2 and task

Nicloas and Sylvain => Creating the ExportDOT class and its methods

Ils ont décidé d'appliquer les suggestions données dans l'évaluation de la PR #6 voici le lien : https://github.com/oliviercailloux-org/projet-j-voting/pull/6

=== Duo 3 and task

Chahid and Lucas => improvement of the GUI and the profile_GUI and implementation of input box and the open/save as button

- implémenter une boite d'entrée rouge
- implémenter un bouton open/save as
- Améliorer la GUI qui permettra de faire un fonctionnement basique 
- Amélioration du package profile_GUI en particulier de editionView

== Iteration 2 JAVA

=== Scrum-Master

Lucas

=== Duo 1 and task

Hugo et Sylvain => Modifications requested in the following PRs :

- PR #15 : https://github.com/oliviercailloux-org/projet-j-voting/pull/15#pullrequestreview-640930502
- PR #16 : https://github.com/oliviercailloux-org/projet-j-voting/pull/16#pullrequestreview-640972921
- PR #17 : https://github.com/oliviercailloux-org/projet-j-voting/pull/17#pullrequestreview-641013709
- PR #18 : https://github.com/oliviercailloux-org/projet-j-voting/pull/18#pullrequestreview-641037660

And test the asGraph () method and implement the asStrictGraph () method.

=== Duo 2 and task

Chahid et Firas => Continue to work on the GUI, PR #20 : https://github.com/oliviercailloux-org/projet-j-voting/pull/20#pullrequestreview-641453976


=== Duo 3 and task

Nicolas et Maxime => ExportDOT, work requested in PR #19 : https://github.com/oliviercailloux-org/projet-j-voting/pull/19#pullrequestreview-641378958 
