= J-Voting
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: j-voting
:repository: J-Voting

image:https://github.com/{gitHubUserName}/{repository}/workflows/J-Voting%20CI/badge.svg["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Last release", link="http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22{groupId}%22%20a%3A%22{artifactId}%22"]
image:http://www.javadoc.io/badge/{groupId}/{artifactId}.svg["Javadoc", link="http://www.javadoc.io/doc/{groupId}/{artifactId}"]

A Java project developed with students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises[L3 MIAGE Alternance]).

The code is hereby published under the MIT License, with the permission of the contributors.

The project documentation is link:Doc/README.adoc[here].

== Iteration UML 1

=== Scrum-Master

Maxime

=== Duo 1 and task

Firas ans Chahid => Documentation of bugs

=== Duo 2 and task

Hugo and Nicolas => Export in DOT format

=== Duo 3 and task

Lucas and Sylvain => Set URL preflib

== Iteration UML 2

=== Scrum-Master

Chahid

=== Duo 1 and task

Firas and Hugo  => Implementation of a class and sequence diagram (Decorator)

=== Duo 2 and task

Lucas and Nicolas => Adjustments and export in DOT format 

=== Duo 3 and task

Maxime and Sylvain => Import an external profile via an url (preflib)

== Iteration UML 3

=== Scrum-Master

Firas

=== Duo 1 and task

Maxime and Hugo  => Complete the class diagram and correct the sequence diagram (Decorator)

=== Duo 2 and task

Nicloas and Sylvain => Documentation package management and MutableCompletePreference 

=== Duo 3 and task

Chahid and Lucas => Improvement of the new GUI and modification of the profile doc

== Iteration UML 4

=== Scrum-Master

Lucas

=== Duo 1 and task

Hugo and Sylvain => Ils continuent le travail commencé dans cette PR #9 : https://github.com/oliviercailloux-org/projet-j-voting/pull/9#pullrequestreview-635973419 .Ils souhaitent corriger et compléter les diagrammes de classe et de séquence liés au decorator.

=== Duo 2 and task

Chahid and Firas => Preflib and GUI, leur travail fait suite à cette PR #11 : https://github.com/oliviercailloux-org/projet-j-voting/pull/11#pullrequestreview-635983537

=== Duo 3 and task

Nicolas and Maxime => DOT export,  enfin, Nicolas et Maxime souhaitent continuer le travail entamé dans cette PR #12 : https://github.com/oliviercailloux-org/projet-j-voting/pull/12#pullrequestreview-636054061

